nome=str(input("Digite seu nome completo:"))
maisc=nome.upper()
minusc=nome.lower()
letras1=len(nome.strip())
espaços=nome.count(" ")
letras2=nome.split()
print("Nome maíusculo: {}".format(maisc))
print("Nome minúsculo: {}".format(minusc))
print("Quantidade de letras no nome sem espaços: {}".format(letras1-espaços))
print("Seu primeiro nome é {} e a quantidade de letras é {}".format(letras2[0],len(letras2[0])))
